<?php

namespace App\Modules\Invoice\Models;

use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Business extends Model
{
    use HasFactory;

    protected $fillable = [
        'company_id',
        'user_id',
        'name',
        'email',
        'phone',
        'address',
        'logo',
        'currency',
        'timezone',
        'tax_number',
        'bank_details',
        'iban',
        'bic',
        'payment_terms',
        'invoice_number_prefix',
        'invoice_number_next',
        'estimate_number_prefix',
        'estimate_number_next',
    ];

    protected $casts = [
        'invoice_number_next' => 'integer',
    ];

    public static function forCompany(Company $company): self
    {
        return self::firstOrCreate(
            ['company_id' => $company->id],
            [
                'user_id' => $company->user_id,
                'name' => $company->name,
                'currency' => $company->currency ?? 'EUR',
                'timezone' => 'UTC',
            ]
        );
    }

    protected static function booted(): void
    {
        static::created(function ($business) {
            $business->seedDefaultTemplates();
        });
    }

    public function seedDefaultTemplates(): void
    {
        $templates = [
            [
                'name' => 'Minimalist Professional',
                'primary_color' => '#1f2937',
                'font_family' => 'Helvetica, sans-serif',
                'header_style' => 'simple',
                'show_tax' => true,
                'show_discount' => true,
                'is_default' => true,
                'payment_terms' => 'Please pay within 15 days.',
                'footer_message' => 'Thank you for your business!',
                'enable_qr' => false,
            ],
            [
                'name' => 'Tech Startup Blue',
                'primary_color' => '#3b82f6',
                'font_family' => 'Arial, sans-serif',
                'header_style' => 'center',
                'show_tax' => true,
                'show_discount' => false,
                'is_default' => false,
                'payment_terms' => 'Payable upon receipt.',
                'footer_message' => 'Built with code & coffee.',
                'enable_qr' => false,
            ],
        ];

        foreach ($templates as $template) {
            $this->templates()->updateOrCreate(
                ['name' => $template['name']],
                $template
            );
        }
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function clients(): HasMany
    {
        return $this->hasMany(Client::class);
    }

    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    public function templates(): HasMany
    {
        return $this->hasMany(Template::class);
    }

    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class);
    }

    public function getCurrencySymbolAttribute(): string
    {
        return match (strtoupper($this->currency)) {
            'USD', 'CAD', 'AUD' => '$',
            'EUR' => '€',
            'GBP' => '£',
            'JPY' => '¥',
            'INR' => '₹',
            'PKR' => 'Rs',
            'AED' => 'د.إ',
            default => $this->currency.' ',
        };
    }

    public function getEpcQrCodeString(Invoice $invoice): ?string
    {
        if (empty($this->iban) || strtoupper($this->currency) !== 'EUR') {
            return null;
        }

        $amount = number_format($invoice->amount_due, 2, '.', '');
        $beneficiaryName = substr($this->name, 0, 70);
        $iban = str_replace(' ', '', $this->iban);
        $bic = str_replace(' ', '', $this->bic);
        $reference = substr($invoice->invoice_number, 0, 140);

        $lines = [
            'BCD',
            '002',
            '1',
            'SCT',
            $bic,
            $beneficiaryName,
            $iban,
            'EUR'.$amount,
            '',
            '',
            $reference,
            'Generated by Allocore',
        ];

        return implode("\r\n", $lines);
    }
}
